### ISSUE TITLE
How can I use this Objective C? 

### ISSUE THREAD

**Issue by kuldeep13990** [profburke/AppLister#3]
can you please guide me how can I use this on objective c?

**Comment by profburke** [comment]
I'm not quite sure what you're asking. Can you provide more details?

**Comment by kuldeep13990** [comment]
@profburke can I get which application use how much data?

**Comment by profburke** [comment]
Do you mean how much disk space the app takes up? Or how much cellular data is being used?

In either case, you're better off looking in Apple's Settings app. For disk space start the Settings app and go to General > Storage & iCloud Usage > Manage Storage. 

For cell data start the Settings app and go to Cellular.

**Comment by kuldeep13990** [comment]
@profburke not a disk space, when I use Facebook, histogram and other app, I want to know Facebook used how much internet data, Instagram used how much data?

**Comment by profburke** [comment]
Then as I mentioned, use Apple's Setting app and tap the Cellular tab.
